# decide if the AntiXRay should be standard activated or deactivated
# true = activated
# false = deactivated
antixray.standard: false

# decide worlds in which the opposite of "antixray.standard" is working
# if "antixray.standard" = true: AntiXRay will be disabled in these worlds
# if "antixray.standard" = false: AntiXRay will be enabled in these worlds
antixray.worlds: []